### ISSUE TITLE
Take rhs_optic_base into account

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/grad-loadout#6]
RHS allows the player to choose which type of weapon optic he prefers (`3D` / `2D` / `PiP`), which can lead to issues with custom gear.
![](https://i.imgur.com/6uGYVrF.jpg)

---

**Take the following example:**

In my mission I allow a series of primary weapon optics to choose from:
```hpp
primaryWeaponOptics[] = { /* [...] */ "rhsusf_acc_su230", /* [...] */};
```

The player has chosen `3D` as his preferred optic type in the RHS settings.
He chooses - or gets randomly assigned - the SU-230/PVS (`rhsusf_acc_su230`).
RHS instantly switches his optic to `rhsusf_acc_su230_3d`, which is the 3D version of the SU-230/PVS.
Custom gear checks if the player has an "allowed item", before letting him change it via custom gear. `rhsusf_acc_su230_3d` is not one of the allowed items, so he won't be able to  switch his weapon optics.

--- 

I haven't had a deeper look, but it seems like RHS has a config value (`rhs_optic_base`) in all its optics, to reference the "base" optic. For our example `rhsusf_acc_su230_3d` has the config entry:
```hpp
rhs_optic_base = "rhsusf_acc_su230";
```

We could check if the item has such a config value and if it does, we would check if that base optic is included in the list of allowed optics.

**Comment by McDiod** [comment]
Fixed in b9c6406. 
Are there any other instances where RHS replaces items (AK variants or something)?

**Comment by DerZade** [comment]
@McDiod Thanks a lot for the quick fix :)

---

The only two additional edge cases I can think of are:

- optics with magnifiers (I don't know if they also have the `rhs_optic_base` config entry; We should take a look at both CBA accessories and the RHS implementation)
- TFAR radios (I think they use a `tf_parent` config entry to reference the base radio)

**Comment by McDiod** [comment]
PR #7 now accounts for RHS and CBA cyclable accessories, as well as TFAR instancing.
